version: "2.0"

nlu:
- intent: action::call
  examples: |
    - call
    - make a call
    - I want to call
    - call [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"}
    - call [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"}
    - call [John's]{"entity": "sort.contact", "value": "individual.contact_john"}
    - call [John]{"entity": "sort.contact", "value": "individual.contact_john"}
    - call [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"}
    - call [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"}
    - call [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"}
    - call [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"}
    - call [john]{"entity": "sort.contact", "value": "individual.contact_john"}
    - call [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"} phone
    - call [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"} phone
    - call [John's]{"entity": "sort.contact", "value": "individual.contact_john"} phone
    - call [John]{"entity": "sort.contact", "value": "individual.contact_john"} phone
    - call [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"} phone
    - call [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"} phone
    - call [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"} phone
    - call [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"} phone
    - call [john]{"entity": "sort.contact", "value": "individual.contact_john"} phone
    - call [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"} [work]{"entity": "sort.phone", "value": "individual.work"}
    - call [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - call [John's]{"entity": "sort.contact", "value": "individual.contact_john"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - call [John]{"entity": "sort.contact", "value": "individual.contact_john"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - call [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"} [work]{"entity": "sort.phone", "value": "individual.work"}
    - call [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"} [work]{"entity": "sort.phone", "value": "individual.work"}
    - call [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"} [work]{"entity": "sort.phone", "value": "individual.work"}
    - call [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"} [home]{"entity": "sort.phone", "value": "individual.home"}
    - call [john]{"entity": "sort.contact", "value": "individual.contact_john"} [work]{"entity": "sort.phone", "value": "individual.work"}

- intent: question::phone_number
  examples: |
    - tell me a phone number
    - I want to know a contact's number
    - what is [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"} [home]{"entity": "sort.phone", "value": "individual.home"}
    - what is [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"} [home]{"entity": "sort.phone", "value": "individual.home"}
    - what is [John's]{"entity": "sort.contact", "value": "individual.contact_john"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - what is [John]{"entity": "sort.contact", "value": "individual.contact_john"} [work]{"entity": "sort.phone", "value": "individual.work"}
    - what is [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"} [work]{"entity": "sort.phone", "value": "individual.work"}
    - what is [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - what is [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - what is [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"} [home]{"entity": "sort.phone", "value": "individual.home"}
    - what is [john]{"entity": "sort.contact", "value": "individual.contact_john"} [work]{"entity": "sort.phone", "value": "individual.work"}
    - what is [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"} number
    - what is [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"} number
    - what is [John's]{"entity": "sort.contact", "value": "individual.contact_john"} number
    - what is [John]{"entity": "sort.contact", "value": "individual.contact_john"} number
    - what is [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"} number
    - what is [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"} number
    - what is [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"} number
    - what is [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"} number
    - what is [john]{"entity": "sort.contact", "value": "individual.contact_john"} number
    - what is [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"} number
    - what is [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"} number
    - what is [John's]{"entity": "sort.contact", "value": "individual.contact_john"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"} number
    - what is [John]{"entity": "sort.contact", "value": "individual.contact_john"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"} number
    - what is [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"} number
    - what is [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"} [work]{"entity": "sort.phone", "value": "individual.work"} number
    - what is [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"} [home]{"entity": "sort.phone", "value": "individual.home"} number
    - what is [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"} [work]{"entity": "sort.phone", "value": "individual.work"} number
    - what is [john]{"entity": "sort.contact", "value": "individual.contact_john"} [work]{"entity": "sort.phone", "value": "individual.work"} number
    - what's [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"} [home]{"entity": "sort.phone", "value": "individual.home"} number
    - what's [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"} [work]{"entity": "sort.phone", "value": "individual.work"} number
    - what's [John's]{"entity": "sort.contact", "value": "individual.contact_john"} [work]{"entity": "sort.phone", "value": "individual.work"} number
    - what's [John]{"entity": "sort.contact", "value": "individual.contact_john"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"} number
    - what's [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"} number
    - what's [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"} [work]{"entity": "sort.phone", "value": "individual.work"} number
    - what's [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"} [mobile]{"entity": "sort.phone", "value": "individual.mobile"} number
    - what's [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"} [home]{"entity": "sort.phone", "value": "individual.home"} number
    - what's [john]{"entity": "sort.contact", "value": "individual.contact_john"} [work]{"entity": "sort.phone", "value": "individual.work"} number

- intent: answer
  examples: |
    - [single](sort.string)
    - [double word](sort.string)
    - [three in one](sort.string)
    - [hey make it four](sort.string)
    - [the more the merrier five](sort.string)
    - [calm down and count to six](sort.string)
    - [bring them through to the jolly seven](sort.string)
    - [noone counts toes like an eight toed guy](sort.string)
    - [it matters to make sense for nine of us](sort.string)
    - [would you bring ten or none to a desert island](sort.string)
    - [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - [mobile phone]{"entity": "sort.phone", "value": "individual.mobile"}
    - [mobile number]{"entity": "sort.phone", "value": "individual.mobile"}
    - [cell]{"entity": "sort.phone", "value": "individual.mobile"}
    - [work]{"entity": "sort.phone", "value": "individual.work"}
    - [work phone]{"entity": "sort.phone", "value": "individual.work"}
    - [work number]{"entity": "sort.phone", "value": "individual.work"}
    - [home]{"entity": "sort.phone", "value": "individual.home"}
    - [home phone]{"entity": "sort.phone", "value": "individual.home"}
    - [home number]{"entity": "sort.phone", "value": "individual.home"}
    - [John]{"entity": "sort.contact", "value": "individual.contact_john"}
    - [John's]{"entity": "sort.contact", "value": "individual.contact_john"}
    - [john]{"entity": "sort.contact", "value": "individual.contact_john"}
    - [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"}
    - [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"}
    - [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"}
    - [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"}
    - [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"}
    - [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"}
    - yes [single](sort.string)
    - yes [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - yes [John]{"entity": "sort.contact", "value": "individual.contact_john"}
    - no [double word](sort.string)
    - no [mobile phone]{"entity": "sort.phone", "value": "individual.mobile"}
    - no [John's]{"entity": "sort.contact", "value": "individual.contact_john"}

- intent: answer_negation
  examples: |
    - not [mobile]{"entity": "sort.phone", "value": "individual.mobile"}
    - not [mobile phone]{"entity": "sort.phone", "value": "individual.mobile"}
    - not [mobile number]{"entity": "sort.phone", "value": "individual.mobile"}
    - not [cell]{"entity": "sort.phone", "value": "individual.mobile"}
    - not [work]{"entity": "sort.phone", "value": "individual.work"}
    - not [work phone]{"entity": "sort.phone", "value": "individual.work"}
    - not [work number]{"entity": "sort.phone", "value": "individual.work"}
    - not [home]{"entity": "sort.phone", "value": "individual.home"}
    - not [home phone]{"entity": "sort.phone", "value": "individual.home"}
    - not [home number]{"entity": "sort.phone", "value": "individual.home"}
    - not [John]{"entity": "sort.contact", "value": "individual.contact_john"}
    - not [John's]{"entity": "sort.contact", "value": "individual.contact_john"}
    - not [john]{"entity": "sort.contact", "value": "individual.contact_john"}
    - not [Mary]{"entity": "sort.contact", "value": "individual.contact_mary"}
    - not [Mary's]{"entity": "sort.contact", "value": "individual.contact_mary"}
    - not [Lisa]{"entity": "sort.contact", "value": "individual.contact_lisa"}
    - not [Lisa's]{"entity": "sort.contact", "value": "individual.contact_lisa"}
    - not [Andy]{"entity": "sort.contact", "value": "individual.contact_andy"}
    - not [Andy's]{"entity": "sort.contact", "value": "individual.contact_andy"}

- intent: NEGATIVE
  examples: |
    - aboard
    - about
    - above
    - across
    - after
    - against
    - along
    - among
    - as
    - at
    - on
    - atop
    - before
    - behind
    - below
    - beneath
    - beside
    - between
    - beyond
    - but
    - by
    - come
    - down
    - during
    - except
    - for
    - from
    - in
    - inside
    - into
    - less
    - like
    - near
    - of
    - off
    - on
    - onto
    - opposite
    - out
    - outside
    - over
    - past
    - save
    - short
    - since
    - than
    - then
    - through
    - throughout
    - to
    - toward
    - under
    - underneath
    - unlike
    - until
    - up
    - upon
    - with
    - within
    - without
    - worth
    - is
    - it
    - the
    - a
    - am
    - are
    - them
    - this
    - that
    - I
    - you
    - he
    - she
    - they
    - them
    - his
    - her
    - my
    - mine
    - their
    - your
    - us
    - our
    - how
    - how's
    - how is
    - how's the
    - how is the
    - when
    - when's
    - when is
    - when is the
    - when's the
    - what
    - what is
    - what's
    - what's the
    - what is the
    - why
    - why is
    - why's
    - why is the
    - why's the
    - do
    - make
    - tell
    - start
    - stop
    - enable
    - disable
    - raise
    - lower
    - decrease
    - increase
    - act
    - determine
    - say
    - ask
    - go
    - shoot
    - wait
    - hang on
    - ok
    - show
    - help

- intent: answer:yes
  examples: |
    - yes
    - yeah
    - yep
    - sure
    - ok
    - of course
    - very well
    - fine
    - right
    - excellent
    - okay
    - perfect
    - I think so

- intent: answer:no
  examples: |
    - no
    - nope
    - no thanks
    - no thank you
    - negative
    - don't want to
    - don't
    - do not
    - please don't

- intent: request:top
  examples: |
    - forget it
    - never mind
    - get me out of here
    - start over
    - beginning
    - never mind that
    - restart

- intent: request:up
  examples: |
    - go back
    - back
    - previous
    - back to the previous
    - go to the previous
    - go back to the previous one

- intent: request:how
  examples: |
    - how do I do that
    - how
    - can you tell me how to do that
    - I don't know how should I do that
    - how can I do that

- intent: report:done
  examples: |
    - I'm done
    - done
    - ready
    - it's ready
    - I'm ready
    - completed
    - check
    - I have finished
    - finished
    - done and done
    - it's done now
    - okay next
    - next
    - next instruction

- intent: icm:per*neg
  examples: |
    - repeat
    - repeat it
    - repeat that
    - pardon
    - sorry
    - can you repeat that
    - excuse me
    - what was that
    - what did you say
    - come again

- intent: icm:acc*neg:issue
  examples: |
    - I don't know
    - I don't know that
    - it doesn't matter

- intent: thanks
  examples: |
    - thank you
    - thank you very much
    - thanks
    - big thanks
    - thanks a lot

- intent: greet
  examples: |
    - hello
    - hi
    - good day
    - what's up
    - good evening
    - good morning
    - hey


